### ISSUE TITLE
Request progress block

### ISSUE THREAD

**Issue by mixdesign** [3lvis/Networking#102]
Haven't found data upload progress block in documentation. Is it planned or forgotten to appear in documentation?

Library looks simple and tasty! Thank you!

**Comment by 3lvis** [comment]
Hi Almas,

I'm happy that you like this library 💐 ! Progress block is not implemented yet. I'll put it in the list. ✅ 

Do you have any preferences? `NSProgress`? Block based params?

**Comment by mixdesign** [comment]
NSProgress. Why not?...

**Comment by aasatt** [comment]
Seconded. A simple variable would be perfect. Like `PHAssetImageProgressHandler`:
     

      networking.progressHandler = { progress in
              print(progress)
        }
