### ISSUE TITLE
Request cancellation

### ISSUE THREAD

**Issue by sgl0v** [3lvis/Networking#104]
This time by calling `cancelRequest` we cancel all requests that match our criteria (urls & http methods are equal). I'd consider using unique identifiers to distinguish requests. As an option, we might use `taskIdentifier` from `NSURLSessionTask` for this.

The updated version would work in the next way:
```
let networking = Networking(baseURL: "http://httpbin.org")
let taskId = networking.GET("/get") { JSON, error in
    // Cancelling a GET request returns an error with code -999 which means cancelled request
}

networking.cancel(taskId)
```

**Comment by 3lvis** [comment]
Hi Max!

You can use `cancelGET("user/12")` to cancel the GET request for the information of the user with ID 12. Isn't that what you want?

**Comment by sgl0v** [comment]
Hello, Elvis. I mean that `cancelRequest` method cancels all sessionTasks that have `HTTPMethod` & `NSURL` equal to the one we provide:

```
    func cancelRequest(sessionTaskType: SessionTaskType, requestType: RequestType, url: NSURL) {
        self.session.getTasksWithCompletionHandler { dataTasks, uploadTasks, downloadTasks in
            var sessionTasks = [NSURLSessionTask]()
            ...

            for sessionTask in sessionTasks {
                if sessionTask.originalRequest?.HTTPMethod == requestType.rawValue && sessionTask.originalRequest?.URL?.absoluteString == url.absoluteString {
                    sessionTask.cancel()
                }
            }
        }
    }
```

As a user I can start N requests by calling `networking.GET("/get") { ...` N times. But there is no way to cancel a particular request. The `networking.cancelGET("/get")` call cancels all of them as you can see from the implementation.

**Comment by 3lvis** [comment]
I see! Would you mind proving some real life use cases so we can make sure we implement the best solution for this?

**Comment by 3lvis** [comment]
the current cancel method wouldn't work for making several POST requests to the same target, since usually post requests share the same path, but have different attributes.

**Comment by sgl0v** [comment]
Yep. Lets assume we are using the REST API and have POST method to create resource or PUT to update resource. For doing this you'll use HTTP body to transmit the data (not query string as for GET). 

Request:
```
POST /resource HTTP/1.1
Host: www.restapi.com
Content-Type: application/x-www-form-urlencoded

field1=value1&field2=value2&field3=value3
```

Response:
```
HTTP/1.1 201 Created
Location: /resource/123
```

In this situation the cancellation won't work as expected.
