### ISSUE TITLE
Return always JSON when its processable

### ISSUE THREAD

**Issue by webventil** [3lvis/Networking#118]
I'm having some problems with an API that returns some detailed information as JSON when serving HTTP 500. I want to read that data and evaluate it. Unfortunately I'm always getting nil.

It would be nice to return this data if it if can be parsed instead of just returning nil, if an HTTP error occurs between outside of 200 till 300.

**Comment by webventil** [comment]
I created a pull request for this #119.

**Comment by 3lvis** [comment]
Fixed on #119
