### ISSUE TITLE
Code=411 "length required"

### ISSUE THREAD

**Issue by ajijoyo** [3lvis/Networking#124]
hello,
i get error when using multipart-data

Error 411: Error Domain=NetworkingErrorDomain Code=411 "length required" UserInfo={NSLocalizedDescription=length required}

**Comment by 3lvis** [comment]
Hi! Maybe your backend requires the file/data length in the header, would you mind giving some specifics to check what's exactly that your backend requires?

**Comment by ajijoyo** [comment]
woooh, done..
thanks...

**Comment by 3lvis** [comment]
I'm glad you got it working ❤️
