### ISSUE TITLE
Add support for using TLS (HTTPS)

### ISSUE THREAD

**Issue by nttravn** [3lvis/Networking#133]
Hello,
I wanna setup https for all connections. So how to config it?
Thanks,

**Comment by 3lvis** [comment]
Could you expand on this? How is that done using NSURLSession?

**Comment by nttravn** [comment]
Hello,
My server is applying https for all requests from app. So I must implement https for it.
Thanks,

**Comment by 3lvis** [comment]
I'm using this with a server that uses HTTPS and I don't have problems. Could you explain what exactly your problem is? 

I use this:

```swift
Networking(baseURL: "https://api.myapp.com")
```

**Comment by 3lvis** [comment]
I'm sure I can find a way to add better support for this if you could share more details :)

**Comment by 3lvis** [comment]
Maybe something related to authentication challenges?

https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/AuthenticationChallenges.html#//apple_ref/doc/uid/TP40009507-SW1

**Comment by nttravn** [comment]
Hi 3lvis,
My server did implement TLS for HTTPS. I will apply a cer file into my project app and configure any request from app to server side for using HTTPS.

I did implement this with Alamofire:
![screen shot 2016-09-29 at 10 06 04 am](https://cloud.githubusercontent.com/assets/3139617/18939705/654dafb2-862c-11e6-87c7-ec61f888a8ee.png)


How to config path to cer file when we use:
self.networking` = Networking(baseURL: "https://api.myapp.com")

Thanks 3lvis :)

**Comment by 3lvis** [comment]
@nttravn Thanks for that! Right now we don't have support for that but I see how it could be useful. I'll try to add it when I got some more time, meanwhile feel free to implement it yourself, sounds like a nice programming excessive to learn more about NSURLSession.

**Comment by nttravn** [comment]
Thanks 3lvis :).
Have a nice day.
