### ISSUE TITLE
Add support for URL encoded GET parameters

### ISSUE THREAD

**Issue by kientux** [3lvis/Networking#153]
AFNetworking has this method:

```
- (NSURLSessionDataTask *)GET:(NSString *)URLString
                   parameters:(id)parameters
                     progress:(void (^)(NSProgress * _Nonnull))downloadProgress
                      success:(void (^)(NSURLSessionDataTask * _Nonnull, id _Nullable))success
                      failure:(void (^)(NSURLSessionDataTask * _Nullable, NSError * _Nonnull))failure;
```

How can I set parameters for GET with Networking? Currently I have to add param to `path` itself.

**Comment by 3lvis** [comment]
It's possible at the moment; what type of backend are you using? Usually you don't send parameters using a GET request.

**Comment by 3lvis** [comment]
In the path you could do like this
```
mypage.html?var1=value1&var2=value2&var3=value3
```

**Comment by kientux** [comment]
Yes I'm doing like that. But that makes it hard to cancel a specific GET request because the path is vary.

**Comment by kientux** [comment]
Yes I'm doing like that. But a param would be more convenient.

**Comment by 3lvis** [comment]
I'll put adding a convenience method for this to the list.

**Comment by 3lvis** [comment]
Do you know by any chance what's the Content-Type that your backend expects for this?

Is it `"application/x-www-form-urlencoded"`?

Or just nothing?

**Comment by 3lvis** [comment]
https://www.w3.org/Protocols/rfc1341/4_Content-Type.html

Looks like should be empty since this is appended to the URL and not to the body.

**Comment by kientux** [comment]
My backend expects the content-type as `"application/json"`. And yes, the parameters of `GET` is just append to the URL, not the body.  So I would say it's just a convenience method, it's not required.

**Comment by hashemp206** [comment]
I really need support for url query encoding. I made a hack in the library to support url encoding for `GET` method with parameters. but I get timed out for secondary searches.

line 465 in `Networking.swift` file

```Swift
var request = URLRequest(url: URL(string: baseURL)!)
        
        if requestType == .GET && parameters != nil{
            guard let parametersDictionary = parameters as? [String : Any] else { fatalError("Couldn't convert parameters to a dictionary: \(parameters)") }
            let formattedParameters = parametersDictionary.formURLEncodedFormat()
            
            request = URLRequest(url: URL(string: baseURL + path + formattedParameters)!)
        } else {
            request = URLRequest(url: self.url(for: path))
        }
        request.httpMethod = requestType.rawValue
```

do you have any idea?

**Comment by 3lvis** [comment]
Hi all,

First of all, thanks for your patience. Things are quite rough this time of the year at work. Christmas gets close and everybody freaks out in Norway. I got some time to wrap this up. I would love your feedback on the final result.

**Comment by kientux** [comment]
It works great!
