### ISSUE TITLE
Swift 3.0.1 incompatibilities?

### ISSUE THREAD

**Issue by GeckoGB** [3lvis/Networking#159]
Hi,

I'm trying to use Networking 2.3.1 with Swift 3.0.1 (XCode 8.1).

I simply create a brand new Cocoa/Swift project, then: "pod init", add 'Networking' to Podfile, and "pod install". Version 2.3.1 is correctly installed.

Then, when opening the workspace, despite Networking is supposed to be Swift 3.0 ready, i have a _"Convert to current Swift syntax?"_ saying that _"Networking contains source code developed with an earlier version of Swift"_.

I choose "Convert" and "Convert to Swift 3". Conversion seems to mainly replacing "public" keyword with "open", and "private" with "fileprivate" (despite a lot of other errors are displayed), but also end with "Failed" message and a lot of errors.

After conversion i clean the project to remove error messages.

Then, when trying to build (from empty project, nothing added or modified), build fail for:
```
    open func authenticate(_ username: String, password: String) {
        self.setAuthorizationHeader(username: username, password: password)
    }

```
and
```
    open func authenticate(_ headerKey: String = "Authorization", headerValue: String) {
        self.setAuthorizationHeader(headerKey: headerKey, headerValue: headerValue)
    }

```
with error _"Argument labels '(username:, password:)' do not match any available overload"_.
And either if i comment out these 2 depracated functions, i have the exact same error when trying to use 'setAuthorizedHeader' in my own code.

Could you please help?

Thanks!
![step1](https://cloud.githubusercontent.com/assets/24299259/20803448/8dc5159e-b7ef-11e6-95a6-b79b7ae3f726.jpg)
![step2a](https://cloud.githubusercontent.com/assets/24299259/20803446/8dc207e6-b7ef-11e6-9d81-a838c2cae7bb.jpg)
![step2b](https://cloud.githubusercontent.com/assets/24299259/20803449/8dcc1718-b7ef-11e6-8112-863726fa4716.jpg)
![step3](https://cloud.githubusercontent.com/assets/24299259/20803447/8dc45410-b7ef-11e6-882f-926f1a489ce0.jpg)

**Comment by 3lvis** [comment]
Hi @GeckoGB, 

This seems like a CocoaPods issue, everything seems to be working fine from my side.

**Comment by 3lvis** [comment]
Please use this project as a demo. It uses Swift 3.0.1 without problems.

https://github.com/3lvis/NetworkingThumbnailPerformance/commit/77b2d1e452c5744613deb3412a321a7cb635fa6e#diff-9ffafd1ecd225c2718bff2ce6a570a03R414

Let me know if you need any help.

**Comment by GeckoGB** [comment]
I don't think so. Pod version 2.3.1 is correctly imported: i've compared (diff) source code from git repository (tag 2.3.1) and file imported by Cocoapod (before XCode conversion): it's exactly the same.
And the 2.3.1 code really include older Swift 2.3 syntax: private, public... So it is normal that XCode complains about syntax and try to convert files, they are not Swift 3.0.

**Comment by 3lvis** [comment]
@GeckoGB could you delete the Podfile.lock and run `pod update`? The latest version should be 2.4.0.

**Comment by GeckoGB** [comment]
Updated: now 2.4.0 installed, but XCode still complains about code from earlier Swift version, and asks to convert to Swift 3. And errors are exactly the same.
Looking at source code (git tag 2.4.0), deprecated Swift 2.3 "private" and "public" keywords are still there. So current code really isn't Swift 3.0.

**Comment by 3lvis** [comment]
That's pretty weird, did you have a chance to look at the https://github.com/3lvis/NetworkingThumbnailPerformance project? It's working fine there.

**Comment by 3lvis** [comment]
@GeckoGB could you share your Podfile here?

**Comment by 3lvis** [comment]
I'm also in https://gitter.im/SwiftNetworking/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link if you need help

**Comment by 3lvis** [comment]
Other things to look at, in your app target check this.

<img width="747" alt="screen shot 2016-12-01 at 20 02 36" src="https://cloud.githubusercontent.com/assets/1088217/20807973/2cbac412-b801-11e6-8a01-a8da1ec083b8.png">

**Comment by GeckoGB** [comment]
Podfile attached.

[Podfile.zip](https://github.com/3lvis/Networking/files/625525/Podfile.zip)

**Comment by GeckoGB** [comment]
Demo project: same conversion message, same errors.
![demo](https://cloud.githubusercontent.com/assets/24299259/20808341/7dd7704c-b802-11e6-82aa-2396f46e0b6a.jpg)

**Comment by GeckoGB** [comment]
Well... I've noticed that pod executable was not the latests, so i've updated it from 1.0.1 to 1.1.1.

Now, `pod install` gives some kind of warnings: _[!] The `test6Tests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-test6Tests/Pods-test6Tests.debug.xcconfig'. This can lead to problems with the CocoaPods installation_

But now project opens **without conversion and compiles correctly**!

What i don't understand, is why, since syntax is not Swift 3.0?!?

But well, it works now.

Thanks for your help!

**Comment by 3lvis** [comment]
Don't worry!
