### ISSUE TITLE
let the Networking extension methods to be public

### ISSUE THREAD

**Issue by jokefaker** [3lvis/Networking#171]
so，can you let Networking extension methods to be public to satisfy some special condition,  for exam we may add a request body to the DELETE method，if it's public, it can be easy to write a extension

**Comment by 3lvis** [comment]
@jokefaker I'll make it open for easier subclassing.

**Comment by 3lvis** [comment]
It's marked as `open` now. I thought DELETE shouldn't have a request body. 

You want something like:

```swift
let networking = Networking(baseURL: "http://httpbin.org")
networking.DELETE("/delete", parameters: ["username" : "jameson", "password" : "secret"]) { json, error in
```

**Comment by 3lvis** [comment]
I think this should be fixed now, otherwise, let me know.
