### ISSUE TITLE
Document synchronous networking in README

### ISSUE THREAD

**Issue by 3lvis** [3lvis/Networking#185]
```swift
public var isSynchronous = false
```

https://github.com/3lvis/Networking/blob/828f3c53e174edc9bbad347821494273c60701fd/Sources/Networking.swift#L141

**Comment by Smiacter** [comment]
I use post with parameters, type is .formURLEncoded, and set isSynchronous = true. but it not work, it's also asynchronous request...

**Comment by 3lvis** [comment]
@Smiacter I'll check it out. Thanks for reporting this!

**Comment by 3lvis** [comment]
Hi @Smiacter,

All the tests are synchronous and I have a test for formURLEncoded and got it working without problems. Could you double check or share an example of what you're doing with me? All is working fine here.

**Comment by Smiacter** [comment]
@3lvis Thanks, I'll check it again.

**Comment by 3lvis** [comment]
This is the unit test I mentioned https://github.com/3lvis/Networking/blob/master/Tests/POSTTests.swift#L91-L114

**Comment by Smiacter** [comment]
@3lvis ok, I'll try it, thanks for your help.
