### ISSUE TITLE
fatalError when body is an invalid image

### ISSUE THREAD

**Issue by nsoojin** [3lvis/Networking#195]
Hi,
Right now app crashes due to the fatal error in the initializer of ImageResult enum when the response body cannot be casted to Image.
But I think this should not be a fatal error because it is a problem from backend and developers can recover from and handle such cases.
So rather than fatal-erroring, how about make it a failure (parsing error perhaps?).
If you think the same way, I'll make a PR

**Comment by 3lvis** [comment]
Hi @nsoojin,

Is this what you were talking about https://github.com/3lvis/Networking/pull/196?

I'm gonna add you as contributor so it's easier for you to contribute :) If you have any suggestions or want to improve anything we can discuss it in Gitter, might make things better.

https://gitter.im/SwiftNetworking/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by 3lvis** [comment]
Fixed in #196

**Comment by nsoojin** [comment]
wow that was fast!
ok thanks :)
looking forward to contribute!

**Comment by 3lvis** [comment]
@nsoojin yay! 💐 

# [Released in Networking 3.0.1](https://github.com/3lvis/Networking/releases/tag/3.0.1)
