### ISSUE TITLE
HttpBody attachement

### ISSUE THREAD

**Issue by ThabreshVivid** [3lvis/Networking#198]
How can I add this lines ?

 let values = ["emailID": "info@info.com"]
 request.httpBody = try! JSONSerialization.data(withJSONObject: values)

**Comment by 3lvis** [comment]
@ThabreshVivid If I understand correctly it should be something like:

```swift
let networking = Networking(baseURL: "http://httpbin.org")
networking.post("/post", parameters: ["emailID" : "info@info.com"]) { result in

}
```

**Comment by ThabreshVivid** [comment]
![screen shot 2017-03-17 at 5 29 09 pm](https://cloud.githubusercontent.com/assets/18044565/24042274/49274650-0b37-11e7-9efc-2091313db842.png)

 
@3lvis here the 7th line I got the error. how to resolve this ?

**Comment by 3lvis** [comment]
@ThabreshVivid you probably need to use

@ThabreshVivid it's parts and needs an array of FormDataPart.

So change it to 

```swift
networking.post("DriverPhotoUpload", parts: [part]) { result in
```

**Comment by ThabreshVivid** [comment]
@3lvis How can I set the content type ??

like this,
networking.post("DriverPhotoUpload", parameterType: .custom("multipart/form-data"), parameters: imageData) { result in

**Comment by 3lvis** [comment]
The content-type is automatically set for you.

**Comment by 3lvis** [comment]
There's a simple example here.

https://github.com/3lvis/Networking/blob/master/Tests/POSTTests.swift#L116-L151

**Comment by ThabreshVivid** [comment]
@3lvis thanks its working too good :)
