### ISSUE TITLE
Handle self signed SSL certificates

### ISSUE THREAD

**Issue by porter707** [3lvis/Networking#202]
Hi, sorry if this is already a feature or explained somewhere but I couldn't find the answer

So when I make a call to a site that has a self signed SSL certificate I get the following response back

========== Networking Error ==========
 
*** Request ***
 
Error -1202: Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “example.com” which could put your confidential information at risk." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x170139780>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9813, NSErrorPeerCertificateChainKey=(
    "<cert(0x1020e6400) s: Parallels Panel i: Parallels Panel>"
), NSUnderlyingError=0x1706539b0 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x170139780>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9813, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9813, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x1020e6400) s: Parallels Panel i: Parallels Panel>"
)}}, NSLocalizedDescription=The certificate for this server is invalid. You might be connecting to a server that is pretending to be “example.com” which could put your confidential information at risk., NSErrorFailingURLKey=https://example.com, NSErrorFailingURLStringKey=https://example.com, NSErrorClientCertificateStateKey=0}

is there a way to continue with the request? thanks

**Comment by 3lvis** [comment]
Hi @porter707,

Could you please help me reproducing the error? I haven't used self signed certificates before.

**Comment by porter707** [comment]
Hi @3lvis,

Sure whats the best way to go about this?

Basically I have a localhost site that I've created a self signed certificate for.

https://www.digitalocean.com/community/tutorials/how-to-create-a-ssl-certificate-on-apache-for-ubuntu-14-04

then when my app makes a post request to the site I get the above error.

I can try and get a public facing site with a self signed certificate up if you can't get a local one?

**Comment by 3lvis** [comment]
@porter707 Could you please send me a private message in Gitter so I can follow up? Maybe I can try using your server.

https://gitter.im/SwiftNetworking/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
