### ISSUE TITLE
Is disable caching possible?

### ISSUE THREAD

**Issue by dorucazan** [3lvis/Networking#206]
Hi,
I am using the library to download data that changes often on server but URL remains. Because of this I need to disable caching mechanism. Is this possible?
Thanks!

**Comment by 3lvis** [comment]
Hi @dorucazan,

We don't support that right now, it caches by default but should be simple to add. You could add a variable to Networking called "isCachingEnabled" by default the value is true, then you can check for this variable before caching

**Comment by 3lvis** [comment]
Should be possible now!

https://github.com/3lvis/Networking/pull/227
