### ISSUE TITLE
Progress Multipart Upload

### ISSUE THREAD

**Issue by SalvatoreAD** [3lvis/Networking#218]
> networking.progressHandler = { progress in
>           print(progress)
>     }

I tried this function but it does not work. Is it possible to know the percentage of upload and download of a request post?

**Comment by 3lvis** [comment]
Hi @SalvatoreAD,

Sorry for not replying before. I don't remember adding a progressHandler...  but surely this is something that should be prioritized.

**Comment by SalvatoreAD** [comment]
@3lvis Thanks, it would be really useful in order to integrate your library completely. The library is really excellent.
