### ISSUE TITLE
Support for url parameters and custom request headers

### ISSUE THREAD

**Issue by mariusfeldmann** [3lvis/Networking#24]
Having support for url parameters and custom request headers would be great!

Should be pretty straightforward. Something along the lines of:

```public func GET(path: String, params: [String: AnyObject], headers: [String: String], completion: (JSON: AnyObject?, error: NSError?) -> ()) ```

What do you think?

**Comment by 3lvis** [comment]
Any use cases?

**Comment by 3lvis** [comment]
This was related to Basic Auth.

**Comment by 3lvis** [comment]
Added basic auth. Should be fine to close this for now.
