### ISSUE TITLE
Expose handleJSONRequest(..)?

### ISSUE THREAD

**Issue by markst** [3lvis/Networking#243]
Would exposing `handleJSONRequest()` every be considered?

I'd like to be able to perform requests conditional on an objects primary key & have control over the caching level. 

i.e:

```swift
let primaryKey = resource.value(forKey: resource.entity.sync_remotePrimaryKey())
self.handleJSONRequest(primaryKey != nil ? .post : .put,
                       path: path,
                       cacheName: nil,
                       parameterType: .json,
                       parameters: values,
                       responseType: .json,
                       cachingLevel: .none) { (result) in
```

**Comment by markst** [comment]
I suppose this would also involve exposing `RequestType` & `ResponseType` enums.

**Comment by 3lvis** [comment]
Hi! I don't think the workaround might make it worthwhile to exposing those endpoints. It looks pretty clean the way you've resolve it.
