### ISSUE TITLE
Can't use Swift 5 Result enum due to interference with custom one. Need to rename?

### ISSUE THREAD

**Issue by mkll** [3lvis/Networking#252]
Attempt to use Swift 5 Result (`Result<Success, Failure>`) within any source file that imports Networking leads to compiler error. As a workaround I renamed Networking's Result to NetResult in local pod repository, but it’s clear that these changes will be overwritten on any subsequent framework update. It seems that here we need a permanent solution that takes into account the conflict of names.

**Comment by 3lvis** [comment]
Good point, we should rename it. Prefixing things with Networking should be the way to go. Would you mind submitting a PR? Otherwise I'll do it when I get more time. Thanks for reporting!

**Comment by mkll** [comment]
Oh, sure, I will submit PR today.

**Comment by mkll** [comment]
https://github.com/3lvis/Networking/pull/253
