### ISSUE TITLE
No waitsForConnectivity support for background request.

### ISSUE THREAD

**Issue by haozes** [3lvis/Networking#262]
Hi.
Thanks for the great code make my life easier. 
And I have not find  **waitsForConnectivity**  support  for  **URLSessionConfiguration**
_
https://developer.apple.com/documentation/foundation/urlsessionconfiguration/2908812-waitsforconnectivity

That is useful for a background request. Is it missed or not?

Thanks

**Comment by 3lvis** [comment]
Hi @haozes, hope you're doing well. `waitsForConnectivity` hasn't been added since nobody has asked for it yet but we could look into it.
