### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by gbanfalvi** [3lvis/Networking#93]
Any possibility of returning response headers in the callback block?

**Comment by 3lvis** [comment]
Hi @ gbanfalvi,

Could you elaborate a bit more on why you need the response headers? Maybe we can find a better solution :)

**Comment by aabdellah** [comment]
Getting the "Link" header for example?

**Comment by 3lvis** [comment]
Getting `Last-Modified` could be another example too.

**Comment by aabdellah** [comment]
For the Link header an integrated parser would be great as well ;)

**Comment by 3lvis** [comment]
@aabdellah What do you mean with integrated parser?

**Comment by aabdellah** [comment]
It could parse the link header value and return  a dictionary with rel keys and link values.
https://tools.ietf.org/html/rfc5988

**Comment by BjornRuud** [comment]
+1 for response headers. I have in several projects used HEAD requests to get the Last-Modified header to check for resource updates. The HTTP header is a nice place to put resource and webservice metadata.

**Comment by 3lvis** [comment]
Basic support for returning response headers has been set in place, it will be officially released on 1.2.0.
