### ISSUE TITLE
Consider handling image cache retrieval under the hood

### ISSUE THREAD

**Issue by rajohns08** [3lvis/Networking#95]
The README states:

> **Retrieving cached image:**

> First download an image like you normally do:

> ```swift
let networking = Networking(baseURL: baseURL)
networking.downloadImage("/image/png") { image, error in
    // Downloaded image
}
```

> Then you would be able to retrieve the image from the cache at any time!

> ```swift
networking.imageFromCache("/image/png") { image in
    // Image from cache, you will get `nil` if no image is found
}
```

I would argue that as a user of the library I'd rather always call `networking.downloadImage()` and be completely agnostic to whether it came from network or cache. Otherwise I litter `if !cached` checks before all my download calls.

**Comment by rajohns08** [comment]
Although if this is accepted, you might need to rename the `downloadImage` api call to something more generic like `getImage`.

**Comment by 3lvis** [comment]
Hi Adam,

That's exactly how `downloadImage` works, the `imageFromCache` method is just a helper method that doesn't hit the network. I'll update the README accordingly.

**Comment by 3lvis** [comment]
Should be much better now. Thanks for pointing that out!
